[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmd = "cd src/frontend && npm install"

[phases.build]
cmd = "cd src/frontend && npm run build"

[phases.start]
cmd = "cd src/frontend && npm run preview -- --host 0.0.0.0 --port $PORT"

[variables]
NODE_ENV = "production" 